version: '3'
services:
  my_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - "./database/data:/var/lib/mysql"
  nginx:
    build: 
      context: ./nginx
    depends_on: 
      - php-fpm
    ports: 
      - "8888:80"
    volumes: 
      - "./source/TechnicalTest:/var/www"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/sites/:/etc/nginx/sites-available"
      - "./nginx/conf.d/:/etc/nginx/conf.d"
      - "./logs:/var/log"
    links:
      - "my_db"
  php-fpm: 
    container_name: sf-console
    build: 
      context: ./php-fpm
    depends_on:   
      - my_db
    volumes:
      - "./source/TechnicalTest:/var/www"
    links:
      - "my_db"
  php-webservice: 
    container_name: php-console
    build: 
      context: ./php-fpm
    volumes: 
      - "./source/WebServiceForTechnicalTest:/var/www"
