version: '3'
services: 
  database:
    build: 
      context: ./database
    environment: 
      - "MYSQL_DATABASE=${DATABASE_NAME}"
      - "MYSQL_USER=${DATABASE_USER}"
      - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}"
    ports: 
      - "5435:5432"
    volumes: 
      - "./database/data:/var/lib/mysql"
    networks:
      - default
  nginx: 
    build: 
      context: ./nginx
    depends_on: 
      - php-fpm
    ports: 
      - "8888:80"
    volumes: 
      - "./source/TechnicalTest:/var/www"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/sites/:/etc/nginx/sites-available"
      - "./nginx/conf.d/:/etc/nginx/conf.d"
      - "./logs:/var/log"
    networks:
      - default
    links:
      - "database"
  php-fpm: 
    container_name: sf-console
    build: 
      context: ./php-fpm
    depends_on:   
      - database
    environment: 
      - "APP_ENV=${APP_ENV}"
      - "APP_SECRET=${APP_SECRET} - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5435/${DATABASE_NAME}"
    volumes: 
      - "./source/TechnicalTest:/var/www"
    networks:
      - default
    links:
      - "database:database"
  php-webservice: 
    container_name: php-console
    build: 
      context: ./php-fpm
    volumes: 
      - "./source/WebServiceForTechnicalTest:/var/www"
    networks:
      - default
